name: studyplugin
version: '${version}'
main: org.mukyang.studyplugin.Studyplugin
api-version: '1.21'
commands:
  setjob:
    description: 플레이어의 직업을 설정합니다.
    usage: /setjob <플레이어> <직업> (사냥꾼, 농부, 광부)
  checkstatus:
    description: 다른 플레이어의 직업, 레벨, 경험치를 확인합니다.
    usage: /checkstatus <플레이어>
